"""added table lifts and created an association table

Revision ID: 61178bff91c0
Revises: 93ea53e21ee6
Create Date: 2025-01-15 10:16:17.385509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61178bff91c0'
down_revision = '93ea53e21ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_lifts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lift_id'], ['lifts.id'], name=op.f('fk_user_lifts_lift_id_lifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_lifts_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'lift_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lifts')
    op.drop_table('lifts')
    # ### end Alembic commands ###
